### ISSUE TITLE
Ensure consistent code formatting.

### ISSUE THREAD

**Issue by ameya98** [e3nn/e3nn-jax#14]
To make it easier to read (and contribute), I propose using the [black](https://github.com/psf/black) code formatting tool.
Very easy to install:
```
pip install black
```
then run:
```
black file.py
```
to format `file.py`.

**Comment by mariogeiger** [comment]
Sure, lets give it a try!

**Comment by SauravMaheshkar** [comment]
You can also use the [**official Github Actions Integration**](https://black.readthedocs.io/en/stable/integrations/github_actions.html) from black viz.

```yaml

- uses: psf/black@stable
  with:
    options: "--check --verbose"
    src: "./src"
    version: "21.5b1"

```
